// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package walletrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A BlockID message contains identifiers to select a block: a height or a
// hash. Specification by hash is not implemented, but may be in the future.
type BlockID struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockID) Reset()         { *m = BlockID{} }
func (m *BlockID) String() string { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()    {}
func (*BlockID) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BlockID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockID.Unmarshal(m, b)
}
func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockID.Marshal(b, m, deterministic)
}
func (m *BlockID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockID.Merge(m, src)
}
func (m *BlockID) XXX_Size() int {
	return xxx_messageInfo_BlockID.Size(m)
}
func (m *BlockID) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockID.DiscardUnknown(m)
}

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockID) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// BlockRange specifies a series of blocks from start to end inclusive.
// Both BlockIDs must be heights; specification by hash is not yet supported.
type BlockRange struct {
	Start                *BlockID `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *BlockID `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRange) Reset()         { *m = BlockRange{} }
func (m *BlockRange) String() string { return proto.CompactTextString(m) }
func (*BlockRange) ProtoMessage()    {}
func (*BlockRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *BlockRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRange.Unmarshal(m, b)
}
func (m *BlockRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRange.Marshal(b, m, deterministic)
}
func (m *BlockRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRange.Merge(m, src)
}
func (m *BlockRange) XXX_Size() int {
	return xxx_messageInfo_BlockRange.Size(m)
}
func (m *BlockRange) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRange.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRange proto.InternalMessageInfo

func (m *BlockRange) GetStart() *BlockID {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *BlockRange) GetEnd() *BlockID {
	if m != nil {
		return m.End
	}
	return nil
}

// A TxFilter contains the information needed to identify a particular
// transaction: either a block and an index, or a direct transaction hash.
// Currently, only specification by hash is supported.
type TxFilter struct {
	Block                *BlockID `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxFilter) Reset()         { *m = TxFilter{} }
func (m *TxFilter) String() string { return proto.CompactTextString(m) }
func (*TxFilter) ProtoMessage()    {}
func (*TxFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *TxFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxFilter.Unmarshal(m, b)
}
func (m *TxFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxFilter.Marshal(b, m, deterministic)
}
func (m *TxFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxFilter.Merge(m, src)
}
func (m *TxFilter) XXX_Size() int {
	return xxx_messageInfo_TxFilter.Size(m)
}
func (m *TxFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TxFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TxFilter proto.InternalMessageInfo

func (m *TxFilter) GetBlock() *BlockID {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *TxFilter) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TxFilter) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// RawTransaction contains the complete transaction data. It also optionally includes
// the block height in which the transaction was included
type RawTransaction struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransaction) Reset()         { *m = RawTransaction{} }
func (m *RawTransaction) String() string { return proto.CompactTextString(m) }
func (*RawTransaction) ProtoMessage()    {}
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *RawTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransaction.Unmarshal(m, b)
}
func (m *RawTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransaction.Marshal(b, m, deterministic)
}
func (m *RawTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransaction.Merge(m, src)
}
func (m *RawTransaction) XXX_Size() int {
	return xxx_messageInfo_RawTransaction.Size(m)
}
func (m *RawTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransaction proto.InternalMessageInfo

func (m *RawTransaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RawTransaction) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// A SendResponse encodes an error code and a string. It is currently used
// only by SendTransaction(). If error code is zero, the operation was
// successful; if non-zero, it and the message specify the failure.
type SendResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SendResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// Chainspec is a placeholder to allow specification of a particular chain fork.
type ChainSpec struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainSpec) Reset()         { *m = ChainSpec{} }
func (m *ChainSpec) String() string { return proto.CompactTextString(m) }
func (*ChainSpec) ProtoMessage()    {}
func (*ChainSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ChainSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainSpec.Unmarshal(m, b)
}
func (m *ChainSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainSpec.Marshal(b, m, deterministic)
}
func (m *ChainSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainSpec.Merge(m, src)
}
func (m *ChainSpec) XXX_Size() int {
	return xxx_messageInfo_ChainSpec.Size(m)
}
func (m *ChainSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ChainSpec proto.InternalMessageInfo

// Empty is for gRPCs that take no arguments, currently only GetLightdInfo.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// LightdInfo returns various information about this lightwalletd instance
// and the state of the blockchain.
type LightdInfo struct {
	Version                 string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Vendor                  string   `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	TaddrSupport            bool     `protobuf:"varint,3,opt,name=taddrSupport,proto3" json:"taddrSupport,omitempty"`
	ChainName               string   `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`
	SaplingActivationHeight uint64   `protobuf:"varint,5,opt,name=saplingActivationHeight,proto3" json:"saplingActivationHeight,omitempty"`
	ConsensusBranchId       string   `protobuf:"bytes,6,opt,name=consensusBranchId,proto3" json:"consensusBranchId,omitempty"`
	BlockHeight             uint64   `protobuf:"varint,7,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *LightdInfo) Reset()         { *m = LightdInfo{} }
func (m *LightdInfo) String() string { return proto.CompactTextString(m) }
func (*LightdInfo) ProtoMessage()    {}
func (*LightdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *LightdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightdInfo.Unmarshal(m, b)
}
func (m *LightdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightdInfo.Marshal(b, m, deterministic)
}
func (m *LightdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightdInfo.Merge(m, src)
}
func (m *LightdInfo) XXX_Size() int {
	return xxx_messageInfo_LightdInfo.Size(m)
}
func (m *LightdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LightdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LightdInfo proto.InternalMessageInfo

func (m *LightdInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LightdInfo) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *LightdInfo) GetTaddrSupport() bool {
	if m != nil {
		return m.TaddrSupport
	}
	return false
}

func (m *LightdInfo) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *LightdInfo) GetSaplingActivationHeight() uint64 {
	if m != nil {
		return m.SaplingActivationHeight
	}
	return 0
}

func (m *LightdInfo) GetConsensusBranchId() string {
	if m != nil {
		return m.ConsensusBranchId
	}
	return ""
}

func (m *LightdInfo) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// TransparentAddressBlockFilter restricts the results to the given address
// or block range.
type TransparentAddressBlockFilter struct {
	Address              string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Range                *BlockRange `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransparentAddressBlockFilter) Reset()         { *m = TransparentAddressBlockFilter{} }
func (m *TransparentAddressBlockFilter) String() string { return proto.CompactTextString(m) }
func (*TransparentAddressBlockFilter) ProtoMessage()    {}
func (*TransparentAddressBlockFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *TransparentAddressBlockFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransparentAddressBlockFilter.Unmarshal(m, b)
}
func (m *TransparentAddressBlockFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransparentAddressBlockFilter.Marshal(b, m, deterministic)
}
func (m *TransparentAddressBlockFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransparentAddressBlockFilter.Merge(m, src)
}
func (m *TransparentAddressBlockFilter) XXX_Size() int {
	return xxx_messageInfo_TransparentAddressBlockFilter.Size(m)
}
func (m *TransparentAddressBlockFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TransparentAddressBlockFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TransparentAddressBlockFilter proto.InternalMessageInfo

func (m *TransparentAddressBlockFilter) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TransparentAddressBlockFilter) GetRange() *BlockRange {
	if m != nil {
		return m.Range
	}
	return nil
}

// Duration is currently used only for testing, so that the Ping rpc
// can simulate a delay, to create many simultaneous connections. Units
// are microseconds.
type Duration struct {
	IntervalUs           int64    `protobuf:"varint,1,opt,name=intervalUs,proto3" json:"intervalUs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetIntervalUs() int64 {
	if m != nil {
		return m.IntervalUs
	}
	return 0
}

// PingResponse is used to indicate concurrency, how many Ping rpcs
// are executing upon entry and upon exit (after the delay).
type PingResponse struct {
	Entry                int64    `protobuf:"varint,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Exit                 int64    `protobuf:"varint,2,opt,name=exit,proto3" json:"exit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetEntry() int64 {
	if m != nil {
		return m.Entry
	}
	return 0
}

func (m *PingResponse) GetExit() int64 {
	if m != nil {
		return m.Exit
	}
	return 0
}

type RegisterNameCommitmentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Controllingaddress   string   `protobuf:"bytes,2,opt,name=controllingaddress,proto3" json:"controllingaddress,omitempty"`
	Referralidentity     string   `protobuf:"bytes,3,opt,name=referralidentity,proto3" json:"referralidentity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNameCommitmentRequest) Reset()         { *m = RegisterNameCommitmentRequest{} }
func (m *RegisterNameCommitmentRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterNameCommitmentRequest) ProtoMessage()    {}
func (*RegisterNameCommitmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *RegisterNameCommitmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNameCommitmentRequest.Unmarshal(m, b)
}
func (m *RegisterNameCommitmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNameCommitmentRequest.Marshal(b, m, deterministic)
}
func (m *RegisterNameCommitmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNameCommitmentRequest.Merge(m, src)
}
func (m *RegisterNameCommitmentRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterNameCommitmentRequest.Size(m)
}
func (m *RegisterNameCommitmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNameCommitmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNameCommitmentRequest proto.InternalMessageInfo

func (m *RegisterNameCommitmentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterNameCommitmentRequest) GetControllingaddress() string {
	if m != nil {
		return m.Controllingaddress
	}
	return ""
}

func (m *RegisterNameCommitmentRequest) GetReferralidentity() string {
	if m != nil {
		return m.Referralidentity
	}
	return ""
}

type NameReservation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Salt                 string   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Referral             string   `protobuf:"bytes,3,opt,name=referral,proto3" json:"referral,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Nameid               string   `protobuf:"bytes,5,opt,name=nameid,proto3" json:"nameid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameReservation) Reset()         { *m = NameReservation{} }
func (m *NameReservation) String() string { return proto.CompactTextString(m) }
func (*NameReservation) ProtoMessage()    {}
func (*NameReservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *NameReservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameReservation.Unmarshal(m, b)
}
func (m *NameReservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameReservation.Marshal(b, m, deterministic)
}
func (m *NameReservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameReservation.Merge(m, src)
}
func (m *NameReservation) XXX_Size() int {
	return xxx_messageInfo_NameReservation.Size(m)
}
func (m *NameReservation) XXX_DiscardUnknown() {
	xxx_messageInfo_NameReservation.DiscardUnknown(m)
}

var xxx_messageInfo_NameReservation proto.InternalMessageInfo

func (m *NameReservation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameReservation) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *NameReservation) GetReferral() string {
	if m != nil {
		return m.Referral
	}
	return ""
}

func (m *NameReservation) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *NameReservation) GetNameid() string {
	if m != nil {
		return m.Nameid
	}
	return ""
}

// Name reservation with txid.
type RegisterNameCommitmentResponse struct {
	Txid                 string           `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Namereservation      *NameReservation `protobuf:"bytes,2,opt,name=namereservation,proto3" json:"namereservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterNameCommitmentResponse) Reset()         { *m = RegisterNameCommitmentResponse{} }
func (m *RegisterNameCommitmentResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterNameCommitmentResponse) ProtoMessage()    {}
func (*RegisterNameCommitmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *RegisterNameCommitmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNameCommitmentResponse.Unmarshal(m, b)
}
func (m *RegisterNameCommitmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNameCommitmentResponse.Marshal(b, m, deterministic)
}
func (m *RegisterNameCommitmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNameCommitmentResponse.Merge(m, src)
}
func (m *RegisterNameCommitmentResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterNameCommitmentResponse.Size(m)
}
func (m *RegisterNameCommitmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNameCommitmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNameCommitmentResponse proto.InternalMessageInfo

func (m *RegisterNameCommitmentResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *RegisterNameCommitmentResponse) GetNamereservation() *NameReservation {
	if m != nil {
		return m.Namereservation
	}
	return nil
}

type Identity struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contentmap           map[string]string `protobuf:"bytes,2,rep,name=contentmap,proto3" json:"contentmap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Primaryaddresses     []string          `protobuf:"bytes,3,rep,name=primaryaddresses,proto3" json:"primaryaddresses,omitempty"`
	Minimumsignatures    uint32            `protobuf:"varint,4,opt,name=minimumsignatures,proto3" json:"minimumsignatures,omitempty"`
	Privateaddress       string            `protobuf:"bytes,5,opt,name=privateaddress,proto3" json:"privateaddress,omitempty"`
	Revocationauthority  string            `protobuf:"bytes,6,opt,name=revocationauthority,proto3" json:"revocationauthority,omitempty"`
	Recoveryauthority    string            `protobuf:"bytes,7,opt,name=recoveryauthority,proto3" json:"recoveryauthority,omitempty"`
	Flags                uint32            `protobuf:"varint,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Version              uint32            `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	Parent               string            `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetContentmap() map[string]string {
	if m != nil {
		return m.Contentmap
	}
	return nil
}

func (m *Identity) GetPrimaryaddresses() []string {
	if m != nil {
		return m.Primaryaddresses
	}
	return nil
}

func (m *Identity) GetMinimumsignatures() uint32 {
	if m != nil {
		return m.Minimumsignatures
	}
	return 0
}

func (m *Identity) GetPrivateaddress() string {
	if m != nil {
		return m.Privateaddress
	}
	return ""
}

func (m *Identity) GetRevocationauthority() string {
	if m != nil {
		return m.Revocationauthority
	}
	return ""
}

func (m *Identity) GetRecoveryauthority() string {
	if m != nil {
		return m.Recoveryauthority
	}
	return ""
}

func (m *Identity) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Identity) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Identity) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type RegisterIdentityRequest struct {
	Txid                 string           `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Namereservation      *NameReservation `protobuf:"bytes,2,opt,name=namereservation,proto3" json:"namereservation,omitempty"`
	Identity             *Identity        `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Feeoffer             float64          `protobuf:"fixed64,4,opt,name=feeoffer,proto3" json:"feeoffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterIdentityRequest) Reset()         { *m = RegisterIdentityRequest{} }
func (m *RegisterIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterIdentityRequest) ProtoMessage()    {}
func (*RegisterIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *RegisterIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterIdentityRequest.Unmarshal(m, b)
}
func (m *RegisterIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterIdentityRequest.Marshal(b, m, deterministic)
}
func (m *RegisterIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterIdentityRequest.Merge(m, src)
}
func (m *RegisterIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterIdentityRequest.Size(m)
}
func (m *RegisterIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterIdentityRequest proto.InternalMessageInfo

func (m *RegisterIdentityRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *RegisterIdentityRequest) GetNamereservation() *NameReservation {
	if m != nil {
		return m.Namereservation
	}
	return nil
}

func (m *RegisterIdentityRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *RegisterIdentityRequest) GetFeeoffer() float64 {
	if m != nil {
		return m.Feeoffer
	}
	return 0
}

type RegisterIdentityResponse struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterIdentityResponse) Reset()         { *m = RegisterIdentityResponse{} }
func (m *RegisterIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterIdentityResponse) ProtoMessage()    {}
func (*RegisterIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *RegisterIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterIdentityResponse.Unmarshal(m, b)
}
func (m *RegisterIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterIdentityResponse.Marshal(b, m, deterministic)
}
func (m *RegisterIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterIdentityResponse.Merge(m, src)
}
func (m *RegisterIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterIdentityResponse.Size(m)
}
func (m *RegisterIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterIdentityResponse proto.InternalMessageInfo

func (m *RegisterIdentityResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type GetIdentityRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentityRequest) Reset()         { *m = GetIdentityRequest{} }
func (m *GetIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*GetIdentityRequest) ProtoMessage()    {}
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{17}
}

func (m *GetIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityRequest.Unmarshal(m, b)
}
func (m *GetIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityRequest.Marshal(b, m, deterministic)
}
func (m *GetIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityRequest.Merge(m, src)
}
func (m *GetIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_GetIdentityRequest.Size(m)
}
func (m *GetIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityRequest proto.InternalMessageInfo

func (m *GetIdentityRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type IdentityInfo struct {
	Identity             *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Status               string    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Canspendfor          bool      `protobuf:"varint,3,opt,name=canspendfor,proto3" json:"canspendfor,omitempty"`
	Cansignfor           bool      `protobuf:"varint,4,opt,name=cansignfor,proto3" json:"cansignfor,omitempty"`
	Blockheight          uint64    `protobuf:"varint,5,opt,name=blockheight,proto3" json:"blockheight,omitempty"`
	Txid                 string    `protobuf:"bytes,6,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout                 uint32    `protobuf:"varint,7,opt,name=vout,proto3" json:"vout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IdentityInfo) Reset()         { *m = IdentityInfo{} }
func (m *IdentityInfo) String() string { return proto.CompactTextString(m) }
func (*IdentityInfo) ProtoMessage()    {}
func (*IdentityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{18}
}

func (m *IdentityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityInfo.Unmarshal(m, b)
}
func (m *IdentityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityInfo.Marshal(b, m, deterministic)
}
func (m *IdentityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityInfo.Merge(m, src)
}
func (m *IdentityInfo) XXX_Size() int {
	return xxx_messageInfo_IdentityInfo.Size(m)
}
func (m *IdentityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityInfo proto.InternalMessageInfo

func (m *IdentityInfo) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *IdentityInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *IdentityInfo) GetCanspendfor() bool {
	if m != nil {
		return m.Canspendfor
	}
	return false
}

func (m *IdentityInfo) GetCansignfor() bool {
	if m != nil {
		return m.Cansignfor
	}
	return false
}

func (m *IdentityInfo) GetBlockheight() uint64 {
	if m != nil {
		return m.Blockheight
	}
	return 0
}

func (m *IdentityInfo) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *IdentityInfo) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

type GetIdentityResponse struct {
	Identityinfo         *IdentityInfo `protobuf:"bytes,1,opt,name=identityinfo,proto3" json:"identityinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetIdentityResponse) Reset()         { *m = GetIdentityResponse{} }
func (m *GetIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*GetIdentityResponse) ProtoMessage()    {}
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{19}
}

func (m *GetIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityResponse.Unmarshal(m, b)
}
func (m *GetIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityResponse.Marshal(b, m, deterministic)
}
func (m *GetIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityResponse.Merge(m, src)
}
func (m *GetIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_GetIdentityResponse.Size(m)
}
func (m *GetIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityResponse proto.InternalMessageInfo

func (m *GetIdentityResponse) GetIdentityinfo() *IdentityInfo {
	if m != nil {
		return m.Identityinfo
	}
	return nil
}

type RevokeIdentityRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeIdentityRequest) Reset()         { *m = RevokeIdentityRequest{} }
func (m *RevokeIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeIdentityRequest) ProtoMessage()    {}
func (*RevokeIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{20}
}

func (m *RevokeIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeIdentityRequest.Unmarshal(m, b)
}
func (m *RevokeIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeIdentityRequest.Marshal(b, m, deterministic)
}
func (m *RevokeIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeIdentityRequest.Merge(m, src)
}
func (m *RevokeIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeIdentityRequest.Size(m)
}
func (m *RevokeIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeIdentityRequest proto.InternalMessageInfo

func (m *RevokeIdentityRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type RevokeIdentityResponse struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeIdentityResponse) Reset()         { *m = RevokeIdentityResponse{} }
func (m *RevokeIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeIdentityResponse) ProtoMessage()    {}
func (*RevokeIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{21}
}

func (m *RevokeIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeIdentityResponse.Unmarshal(m, b)
}
func (m *RevokeIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeIdentityResponse.Marshal(b, m, deterministic)
}
func (m *RevokeIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeIdentityResponse.Merge(m, src)
}
func (m *RevokeIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeIdentityResponse.Size(m)
}
func (m *RevokeIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeIdentityResponse proto.InternalMessageInfo

func (m *RevokeIdentityResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type RecoverIdentityRequest struct {
	Identity             *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecoverIdentityRequest) Reset()         { *m = RecoverIdentityRequest{} }
func (m *RecoverIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverIdentityRequest) ProtoMessage()    {}
func (*RecoverIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{22}
}

func (m *RecoverIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverIdentityRequest.Unmarshal(m, b)
}
func (m *RecoverIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverIdentityRequest.Marshal(b, m, deterministic)
}
func (m *RecoverIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverIdentityRequest.Merge(m, src)
}
func (m *RecoverIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverIdentityRequest.Size(m)
}
func (m *RecoverIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverIdentityRequest proto.InternalMessageInfo

func (m *RecoverIdentityRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

type RecoverIdentityResponse struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverIdentityResponse) Reset()         { *m = RecoverIdentityResponse{} }
func (m *RecoverIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverIdentityResponse) ProtoMessage()    {}
func (*RecoverIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{23}
}

func (m *RecoverIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverIdentityResponse.Unmarshal(m, b)
}
func (m *RecoverIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverIdentityResponse.Marshal(b, m, deterministic)
}
func (m *RecoverIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverIdentityResponse.Merge(m, src)
}
func (m *RecoverIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_RecoverIdentityResponse.Size(m)
}
func (m *RecoverIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverIdentityResponse proto.InternalMessageInfo

func (m *RecoverIdentityResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type UpdateIdentityRequest struct {
	Identity             *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateIdentityRequest) Reset()         { *m = UpdateIdentityRequest{} }
func (m *UpdateIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIdentityRequest) ProtoMessage()    {}
func (*UpdateIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{24}
}

func (m *UpdateIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIdentityRequest.Unmarshal(m, b)
}
func (m *UpdateIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIdentityRequest.Marshal(b, m, deterministic)
}
func (m *UpdateIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIdentityRequest.Merge(m, src)
}
func (m *UpdateIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateIdentityRequest.Size(m)
}
func (m *UpdateIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIdentityRequest proto.InternalMessageInfo

func (m *UpdateIdentityRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

type UpdateIdentityResponse struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIdentityResponse) Reset()         { *m = UpdateIdentityResponse{} }
func (m *UpdateIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateIdentityResponse) ProtoMessage()    {}
func (*UpdateIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{25}
}

func (m *UpdateIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIdentityResponse.Unmarshal(m, b)
}
func (m *UpdateIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIdentityResponse.Marshal(b, m, deterministic)
}
func (m *UpdateIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIdentityResponse.Merge(m, src)
}
func (m *UpdateIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateIdentityResponse.Size(m)
}
func (m *UpdateIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIdentityResponse proto.InternalMessageInfo

func (m *UpdateIdentityResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type VerifyMessageRequest struct {
	Signer               string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Checklatest          bool     `protobuf:"varint,4,opt,name=checklatest,proto3" json:"checklatest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyMessageRequest) Reset()         { *m = VerifyMessageRequest{} }
func (m *VerifyMessageRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyMessageRequest) ProtoMessage()    {}
func (*VerifyMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{26}
}

func (m *VerifyMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyMessageRequest.Unmarshal(m, b)
}
func (m *VerifyMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyMessageRequest.Marshal(b, m, deterministic)
}
func (m *VerifyMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyMessageRequest.Merge(m, src)
}
func (m *VerifyMessageRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyMessageRequest.Size(m)
}
func (m *VerifyMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyMessageRequest proto.InternalMessageInfo

func (m *VerifyMessageRequest) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *VerifyMessageRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *VerifyMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyMessageRequest) GetChecklatest() bool {
	if m != nil {
		return m.Checklatest
	}
	return false
}

type VerifyMessageResponse struct {
	Signatureisvalid     bool     `protobuf:"varint,1,opt,name=signatureisvalid,proto3" json:"signatureisvalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyMessageResponse) Reset()         { *m = VerifyMessageResponse{} }
func (m *VerifyMessageResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyMessageResponse) ProtoMessage()    {}
func (*VerifyMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{27}
}

func (m *VerifyMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyMessageResponse.Unmarshal(m, b)
}
func (m *VerifyMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyMessageResponse.Marshal(b, m, deterministic)
}
func (m *VerifyMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyMessageResponse.Merge(m, src)
}
func (m *VerifyMessageResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyMessageResponse.Size(m)
}
func (m *VerifyMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyMessageResponse proto.InternalMessageInfo

func (m *VerifyMessageResponse) GetSignatureisvalid() bool {
	if m != nil {
		return m.Signatureisvalid
	}
	return false
}

type VerifyHashRequest struct {
	Signer               string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Checklatest          bool     `protobuf:"varint,4,opt,name=checklatest,proto3" json:"checklatest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyHashRequest) Reset()         { *m = VerifyHashRequest{} }
func (m *VerifyHashRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyHashRequest) ProtoMessage()    {}
func (*VerifyHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{28}
}

func (m *VerifyHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyHashRequest.Unmarshal(m, b)
}
func (m *VerifyHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyHashRequest.Marshal(b, m, deterministic)
}
func (m *VerifyHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyHashRequest.Merge(m, src)
}
func (m *VerifyHashRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyHashRequest.Size(m)
}
func (m *VerifyHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyHashRequest proto.InternalMessageInfo

func (m *VerifyHashRequest) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *VerifyHashRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *VerifyHashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *VerifyHashRequest) GetChecklatest() bool {
	if m != nil {
		return m.Checklatest
	}
	return false
}

type VerifyHashResponse struct {
	Signatureisvalid     bool     `protobuf:"varint,1,opt,name=signatureisvalid,proto3" json:"signatureisvalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyHashResponse) Reset()         { *m = VerifyHashResponse{} }
func (m *VerifyHashResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyHashResponse) ProtoMessage()    {}
func (*VerifyHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{29}
}

func (m *VerifyHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyHashResponse.Unmarshal(m, b)
}
func (m *VerifyHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyHashResponse.Marshal(b, m, deterministic)
}
func (m *VerifyHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyHashResponse.Merge(m, src)
}
func (m *VerifyHashResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyHashResponse.Size(m)
}
func (m *VerifyHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyHashResponse proto.InternalMessageInfo

func (m *VerifyHashResponse) GetSignatureisvalid() bool {
	if m != nil {
		return m.Signatureisvalid
	}
	return false
}

func init() {
	proto.RegisterType((*BlockID)(nil), "cash.z.wallet.sdk.rpc.BlockID")
	proto.RegisterType((*BlockRange)(nil), "cash.z.wallet.sdk.rpc.BlockRange")
	proto.RegisterType((*TxFilter)(nil), "cash.z.wallet.sdk.rpc.TxFilter")
	proto.RegisterType((*RawTransaction)(nil), "cash.z.wallet.sdk.rpc.RawTransaction")
	proto.RegisterType((*SendResponse)(nil), "cash.z.wallet.sdk.rpc.SendResponse")
	proto.RegisterType((*ChainSpec)(nil), "cash.z.wallet.sdk.rpc.ChainSpec")
	proto.RegisterType((*Empty)(nil), "cash.z.wallet.sdk.rpc.Empty")
	proto.RegisterType((*LightdInfo)(nil), "cash.z.wallet.sdk.rpc.LightdInfo")
	proto.RegisterType((*TransparentAddressBlockFilter)(nil), "cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter")
	proto.RegisterType((*Duration)(nil), "cash.z.wallet.sdk.rpc.Duration")
	proto.RegisterType((*PingResponse)(nil), "cash.z.wallet.sdk.rpc.PingResponse")
	proto.RegisterType((*RegisterNameCommitmentRequest)(nil), "cash.z.wallet.sdk.rpc.RegisterNameCommitmentRequest")
	proto.RegisterType((*NameReservation)(nil), "cash.z.wallet.sdk.rpc.NameReservation")
	proto.RegisterType((*RegisterNameCommitmentResponse)(nil), "cash.z.wallet.sdk.rpc.RegisterNameCommitmentResponse")
	proto.RegisterType((*Identity)(nil), "cash.z.wallet.sdk.rpc.Identity")
	proto.RegisterMapType((map[string]string)(nil), "cash.z.wallet.sdk.rpc.Identity.ContentmapEntry")
	proto.RegisterType((*RegisterIdentityRequest)(nil), "cash.z.wallet.sdk.rpc.RegisterIdentityRequest")
	proto.RegisterType((*RegisterIdentityResponse)(nil), "cash.z.wallet.sdk.rpc.RegisterIdentityResponse")
	proto.RegisterType((*GetIdentityRequest)(nil), "cash.z.wallet.sdk.rpc.GetIdentityRequest")
	proto.RegisterType((*IdentityInfo)(nil), "cash.z.wallet.sdk.rpc.IdentityInfo")
	proto.RegisterType((*GetIdentityResponse)(nil), "cash.z.wallet.sdk.rpc.GetIdentityResponse")
	proto.RegisterType((*RevokeIdentityRequest)(nil), "cash.z.wallet.sdk.rpc.RevokeIdentityRequest")
	proto.RegisterType((*RevokeIdentityResponse)(nil), "cash.z.wallet.sdk.rpc.RevokeIdentityResponse")
	proto.RegisterType((*RecoverIdentityRequest)(nil), "cash.z.wallet.sdk.rpc.RecoverIdentityRequest")
	proto.RegisterType((*RecoverIdentityResponse)(nil), "cash.z.wallet.sdk.rpc.RecoverIdentityResponse")
	proto.RegisterType((*UpdateIdentityRequest)(nil), "cash.z.wallet.sdk.rpc.UpdateIdentityRequest")
	proto.RegisterType((*UpdateIdentityResponse)(nil), "cash.z.wallet.sdk.rpc.UpdateIdentityResponse")
	proto.RegisterType((*VerifyMessageRequest)(nil), "cash.z.wallet.sdk.rpc.VerifyMessageRequest")
	proto.RegisterType((*VerifyMessageResponse)(nil), "cash.z.wallet.sdk.rpc.VerifyMessageResponse")
	proto.RegisterType((*VerifyHashRequest)(nil), "cash.z.wallet.sdk.rpc.VerifyHashRequest")
	proto.RegisterType((*VerifyHashResponse)(nil), "cash.z.wallet.sdk.rpc.VerifyHashResponse")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 1516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x18, 0x5d, 0x6f, 0x13, 0xc7,
	0xd6, 0x8e, 0x9d, 0xc4, 0x3e, 0xf9, 0x64, 0x20, 0xc1, 0x5a, 0x01, 0x37, 0x77, 0xae, 0x2e, 0x0a,
	0xb9, 0xc1, 0x44, 0x01, 0x74, 0x51, 0x69, 0xa5, 0x42, 0xa0, 0x21, 0x12, 0xa5, 0x74, 0x12, 0xfa,
	0x40, 0xa5, 0xa2, 0x61, 0xf7, 0xd8, 0xde, 0xc6, 0xde, 0xdd, 0xce, 0x8c, 0x4d, 0xd2, 0x97, 0xf6,
	0xa5, 0x1f, 0xea, 0x4b, 0xff, 0x4f, 0x7f, 0x09, 0xff, 0xa2, 0x7f, 0xa1, 0x9a, 0xd9, 0xd9, 0xcd,
	0x7a, 0xed, 0x8d, 0x1d, 0xd1, 0xbe, 0xcd, 0x39, 0x7b, 0xbe, 0x3f, 0x67, 0x16, 0x96, 0x24, 0x8a,
	0x81, 0xef, 0x62, 0x33, 0x12, 0xa1, 0x0a, 0xc9, 0x9a, 0xcb, 0x65, 0xa7, 0xf9, 0x7d, 0xf3, 0x1d,
	0xef, 0x76, 0x51, 0x35, 0xa5, 0x77, 0xdc, 0x14, 0x91, 0xeb, 0xac, 0xb9, 0x61, 0x2f, 0xe2, 0xae,
	0x7a, 0xd3, 0x0a, 0x45, 0x8f, 0x2b, 0x19, 0x53, 0xd3, 0xfb, 0x30, 0xff, 0xb8, 0x1b, 0xba, 0xc7,
	0x07, 0x4f, 0xc8, 0x3a, 0xcc, 0x75, 0xd0, 0x6f, 0x77, 0x54, 0xa3, 0xbc, 0x51, 0xde, 0xac, 0x32,
	0x0b, 0x11, 0x02, 0xd5, 0x0e, 0x97, 0x9d, 0xc6, 0xcc, 0x46, 0x79, 0x73, 0x91, 0x99, 0x33, 0x55,
	0x00, 0x86, 0x8d, 0xf1, 0xa0, 0x8d, 0xe4, 0x1e, 0xcc, 0x4a, 0xc5, 0x45, 0xcc, 0xb8, 0xb0, 0x7b,
	0xa3, 0x39, 0xd6, 0x84, 0xa6, 0x55, 0xc4, 0x62, 0x62, 0xb2, 0x03, 0x15, 0x0c, 0x3c, 0x23, 0x76,
	0x32, 0x8f, 0x26, 0xa5, 0xdf, 0x42, 0xed, 0xe8, 0xe4, 0x33, 0xbf, 0xab, 0x50, 0x68, 0x9d, 0x6f,
	0xf5, 0xb7, 0x69, 0x75, 0x1a, 0x62, 0x72, 0x05, 0x66, 0xfd, 0xc0, 0xc3, 0x13, 0xa3, 0xb5, 0xca,
	0x62, 0x20, 0xf5, 0xb0, 0x92, 0xf1, 0xf0, 0x63, 0x58, 0x66, 0xfc, 0xdd, 0x91, 0xe0, 0x81, 0xe4,
	0xae, 0xf2, 0xc3, 0x40, 0x53, 0x79, 0x5c, 0x71, 0xa3, 0x70, 0x91, 0x99, 0x73, 0x26, 0x66, 0x33,
	0xd9, 0x98, 0xd1, 0x97, 0xb0, 0x78, 0x88, 0x81, 0xc7, 0x50, 0x46, 0x61, 0x20, 0x91, 0x5c, 0x83,
	0x3a, 0x0a, 0x11, 0x8a, 0xbd, 0xd0, 0x43, 0x23, 0x60, 0x96, 0x9d, 0x21, 0x08, 0x85, 0x45, 0x03,
	0x7c, 0x8e, 0x52, 0xf2, 0x36, 0x1a, 0x59, 0x75, 0x36, 0x84, 0xa3, 0x0b, 0x50, 0xdf, 0xeb, 0x70,
	0x3f, 0x38, 0x8c, 0xd0, 0xa5, 0xf3, 0x30, 0xfb, 0xb4, 0x17, 0xa9, 0x53, 0xfa, 0xdb, 0x0c, 0xc0,
	0x73, 0xad, 0xd1, 0x3b, 0x08, 0x5a, 0x21, 0x69, 0xc0, 0xfc, 0x00, 0x85, 0xf4, 0xc3, 0xc0, 0x28,
	0xa9, 0xb3, 0x04, 0xd4, 0x86, 0x0e, 0x30, 0xf0, 0x42, 0x61, 0x85, 0x5b, 0x48, 0xab, 0x56, 0xdc,
	0xf3, 0xc4, 0x61, 0x3f, 0x8a, 0x42, 0xa1, 0x4c, 0x08, 0x6a, 0x6c, 0x08, 0xa7, 0x8d, 0x77, 0xb5,
	0xea, 0x17, 0xbc, 0x87, 0x8d, 0xaa, 0x61, 0x3f, 0x43, 0x90, 0x07, 0x70, 0x55, 0xf2, 0xa8, 0xeb,
	0x07, 0xed, 0x47, 0xae, 0xf2, 0x07, 0x5c, 0xc7, 0xea, 0x59, 0x1c, 0x93, 0x59, 0x13, 0x93, 0xa2,
	0xcf, 0x64, 0x1b, 0x2e, 0xb9, 0x3a, 0x3a, 0x81, 0xec, 0xcb, 0xc7, 0x82, 0x07, 0x6e, 0xe7, 0xc0,
	0x6b, 0xcc, 0x19, 0xf9, 0xa3, 0x1f, 0xc8, 0x06, 0x2c, 0x98, 0x1c, 0x5a, 0xd9, 0xf3, 0x46, 0x76,
	0x16, 0x45, 0x05, 0x5c, 0x37, 0xf9, 0x8a, 0xb8, 0xc0, 0x40, 0x3d, 0xf2, 0x3c, 0x81, 0x52, 0x9a,
	0x02, 0xb0, 0x35, 0xd3, 0x80, 0x79, 0x1e, 0x63, 0x93, 0xf0, 0x58, 0x90, 0xfc, 0x1f, 0x66, 0x85,
	0x2e, 0x65, 0x5b, 0x8d, 0xff, 0x3e, 0xaf, 0x9a, 0x4c, 0xcd, 0xb3, 0x98, 0x9e, 0x6e, 0x41, 0xed,
	0x49, 0x5f, 0x18, 0xaf, 0xc8, 0x0d, 0x00, 0x3f, 0x50, 0x28, 0x06, 0xbc, 0xfb, 0x2a, 0xd6, 0x50,
	0x61, 0x19, 0x0c, 0x7d, 0x00, 0x8b, 0x2f, 0xfd, 0xa0, 0x9d, 0x16, 0xc5, 0x15, 0x98, 0xc5, 0x40,
	0x89, 0x53, 0x4b, 0x1a, 0x03, 0xba, 0xcc, 0xf0, 0xc4, 0x8f, 0x0b, 0xaa, 0xc2, 0xcc, 0x99, 0xfe,
	0x5e, 0x86, 0xeb, 0x0c, 0xdb, 0xbe, 0x54, 0x28, 0x74, 0xd0, 0xf7, 0xc2, 0x5e, 0xcf, 0x57, 0x3d,
	0x0c, 0x14, 0xc3, 0xef, 0xfa, 0x28, 0x4d, 0x93, 0x06, 0x3a, 0x3d, 0xb1, 0x5f, 0xe6, 0x4c, 0x9a,
	0x40, 0xdc, 0x30, 0x50, 0x22, 0xec, 0xea, 0xf0, 0x27, 0x9e, 0xc7, 0xf9, 0x1f, 0xf3, 0x85, 0x6c,
	0xc1, 0xaa, 0xc0, 0x16, 0x0a, 0xc1, 0xbb, 0xbe, 0x87, 0x81, 0xf2, 0xd5, 0xa9, 0xa9, 0x87, 0x3a,
	0x1b, 0xc1, 0xd3, 0x9f, 0xca, 0xb0, 0xa2, 0x2d, 0x61, 0xa8, 0xa7, 0x0f, 0x4f, 0x1a, 0x64, 0xc4,
	0x06, 0x02, 0x55, 0xc9, 0xbb, 0xca, 0x6a, 0x35, 0x67, 0xe2, 0x40, 0x2d, 0x91, 0x67, 0xe5, 0xa7,
	0xb0, 0xae, 0xd3, 0x38, 0x7d, 0xb6, 0xd0, 0x2c, 0xa4, 0xf1, 0x5a, 0x9e, 0xef, 0x99, 0xa2, 0xaa,
	0x33, 0x0b, 0xd1, 0x9f, 0xcb, 0x70, 0xa3, 0x28, 0x32, 0x36, 0xcc, 0x04, 0xaa, 0xea, 0xc4, 0xf7,
	0x12, 0xb3, 0xf4, 0x99, 0xbc, 0x84, 0x15, 0x2d, 0x40, 0x9c, 0x59, 0x6f, 0x33, 0x7f, 0xb3, 0x20,
	0xf3, 0x39, 0x5f, 0x59, 0x9e, 0x9d, 0xbe, 0xaf, 0x40, 0xed, 0xc0, 0x46, 0x67, 0x6c, 0x24, 0xbe,
	0x00, 0xd0, 0x31, 0xc7, 0x40, 0xf5, 0x78, 0xd4, 0x98, 0xd9, 0xa8, 0x6c, 0x2e, 0xec, 0xde, 0x29,
	0xd0, 0x96, 0x08, 0x6a, 0xee, 0xa5, 0x1c, 0x4f, 0x75, 0x71, 0xb0, 0x8c, 0x08, 0x9d, 0xae, 0x48,
	0xf8, 0x3d, 0x2e, 0x4e, 0x6d, 0x02, 0x51, 0x36, 0x2a, 0x1b, 0x15, 0x9d, 0xae, 0x3c, 0x5e, 0xb7,
	0x5a, 0xcf, 0x0f, 0xfc, 0x5e, 0xbf, 0x27, 0xfd, 0x76, 0xc0, 0x55, 0x5f, 0xa0, 0x34, 0x11, 0x5e,
	0x62, 0xa3, 0x1f, 0xc8, 0x4d, 0x58, 0x8e, 0x84, 0xee, 0x55, 0x4c, 0x8a, 0x26, 0x0e, 0x7a, 0x0e,
	0x4b, 0x76, 0xe0, 0xb2, 0xc0, 0x41, 0xe8, 0x9a, 0x08, 0xf0, 0xbe, 0xea, 0x84, 0x42, 0xd7, 0x4c,
	0xdc, 0xc2, 0xe3, 0x3e, 0x69, 0x3b, 0x04, 0xba, 0xe1, 0x00, 0xc5, 0xe9, 0x19, 0xfd, 0x7c, 0xdc,
	0xf2, 0x23, 0x1f, 0x74, 0x83, 0xb4, 0xba, 0xbc, 0x2d, 0x1b, 0x35, 0x63, 0x69, 0x0c, 0x64, 0x87,
	0x5c, 0xdd, 0xe0, 0xb3, 0x43, 0xce, 0x16, 0x0f, 0x64, 0x8b, 0xc7, 0xf9, 0x04, 0x56, 0x72, 0x81,
	0x24, 0xab, 0x50, 0x39, 0xc6, 0x53, 0x9b, 0x20, 0x7d, 0xd4, 0xca, 0x06, 0xbc, 0xdb, 0x4f, 0xa6,
	0x6f, 0x0c, 0x7c, 0x34, 0xf3, 0xa0, 0x4c, 0xdf, 0x97, 0xe1, 0x6a, 0x52, 0x63, 0x49, 0x66, 0x32,
	0x7d, 0xf7, 0xcf, 0x17, 0x17, 0x79, 0x08, 0xb5, 0xa1, 0x8e, 0x5c, 0xd8, 0xfd, 0xd7, 0x84, 0xca,
	0x61, 0x29, 0x83, 0x6e, 0xb7, 0x16, 0x62, 0xd8, 0x6a, 0xa1, 0x30, 0x29, 0x2f, 0xb3, 0x14, 0xa6,
	0x4d, 0x68, 0x8c, 0x7a, 0x56, 0xdc, 0x37, 0x74, 0x07, 0xc8, 0x3e, 0xaa, 0x7c, 0x10, 0x9c, 0x8c,
	0x79, 0x31, 0x75, 0x0a, 0xd3, 0x3f, 0xcb, 0xb0, 0x98, 0xd0, 0x9b, 0x1d, 0xf5, 0x30, 0x47, 0x7c,
	0x21, 0x5f, 0xd6, 0x61, 0x4e, 0x2a, 0xae, 0xfa, 0xc9, 0x18, 0xb3, 0x90, 0x5e, 0x0e, 0xae, 0x9e,
	0xfc, 0x18, 0x78, 0xad, 0x50, 0xd8, 0x2d, 0x96, 0x45, 0xe9, 0xe1, 0xac, 0x41, 0xbf, 0x1d, 0x68,
	0x82, 0xaa, 0x21, 0xc8, 0x60, 0xd2, 0xf5, 0xd2, 0xc9, 0xae, 0xae, 0x2c, 0x2a, 0x8d, 0xc7, 0x5c,
	0x26, 0xd5, 0x04, 0xaa, 0x83, 0xb0, 0x1f, 0x6f, 0xa3, 0x25, 0x66, 0xce, 0xf4, 0x1b, 0xb8, 0x3c,
	0x14, 0x23, 0x1b, 0xce, 0x7d, 0x58, 0x4c, 0xdc, 0xf0, 0x83, 0x56, 0x68, 0x7d, 0xff, 0xcf, 0x04,
	0xdf, 0x75, 0xc8, 0xd8, 0x10, 0x23, 0xbd, 0x0b, 0x6b, 0x0c, 0x07, 0xe1, 0x31, 0x5e, 0x24, 0x0d,
	0xdb, 0xb0, 0x9e, 0x67, 0x3a, 0x27, 0xcd, 0xaf, 0x34, 0xb5, 0xe9, 0xc6, 0xbc, 0x8e, 0x0f, 0xc9,
	0x1e, 0xbd, 0xad, 0xfb, 0x28, 0x27, 0xf6, 0x1c, 0x2b, 0x8e, 0x60, 0xed, 0x55, 0xe4, 0x71, 0x85,
	0x7f, 0xab, 0x11, 0xdb, 0xb0, 0x9e, 0x97, 0x7a, 0x8e, 0x0d, 0xbf, 0x96, 0xe1, 0xca, 0x57, 0x28,
	0xfc, 0xd6, 0xa9, 0xbd, 0x88, 0x25, 0x36, 0xe8, 0x4a, 0xf4, 0xdb, 0x01, 0x0a, 0x4b, 0x6e, 0x21,
	0x7d, 0x59, 0x4a, 0x27, 0xa9, 0x2d, 0xd2, 0x33, 0x84, 0x9e, 0x5d, 0x3d, 0x7b, 0xc9, 0x8b, 0x37,
	0x5f, 0x02, 0x9a, 0x0a, 0xee, 0xa0, 0x7b, 0xdc, 0xe5, 0x0a, 0xa5, 0xb2, 0x05, 0x9a, 0x45, 0xd1,
	0x3d, 0x58, 0xcb, 0x59, 0x62, 0xed, 0xde, 0x82, 0xd5, 0x54, 0x83, 0x2f, 0x07, 0x7a, 0x4b, 0x1b,
	0xa3, 0x6a, 0x6c, 0x04, 0x4f, 0x7f, 0x80, 0x4b, 0xb1, 0x90, 0x67, 0x5c, 0x76, 0x3e, 0xcc, 0x97,
	0xec, 0xad, 0xb9, 0x1e, 0xdf, 0x9a, 0xa7, 0xf0, 0xe2, 0x53, 0x20, 0x59, 0x03, 0x2e, 0xee, 0xc2,
	0xee, 0x8f, 0x4b, 0x70, 0x69, 0x2f, 0x7e, 0xcc, 0x1c, 0x9d, 0x1c, 0x2a, 0x81, 0x7a, 0x58, 0x92,
	0x23, 0x58, 0xde, 0x47, 0xf5, 0xdc, 0x28, 0x31, 0xd7, 0x34, 0xb2, 0x51, 0x50, 0x13, 0xe9, 0x35,
	0xda, 0x99, 0xf0, 0x68, 0xa0, 0x25, 0xf2, 0x25, 0xd4, 0xf6, 0xd1, 0xca, 0x9b, 0x40, 0xed, 0x14,
	0xb5, 0xb2, 0xb5, 0xd5, 0x90, 0xd1, 0x12, 0xf9, 0x1a, 0x96, 0x12, 0x91, 0xf1, 0xeb, 0x69, 0xf2,
	0x65, 0x73, 0x4a, 0xd1, 0x3b, 0x65, 0xf2, 0xda, 0x44, 0x21, 0xfb, 0x6a, 0x29, 0xea, 0x8c, 0xe4,
	0x21, 0xe5, 0xfc, 0xb7, 0x80, 0x60, 0xf8, 0xf5, 0x43, 0x4b, 0xe4, 0x0d, 0xac, 0xe8, 0x37, 0x4d,
	0x56, 0xf8, 0x74, 0xbc, 0x85, 0xe6, 0x67, 0x9f, 0x48, 0xb4, 0x44, 0x04, 0xac, 0xec, 0x63, 0x72,
	0x6f, 0x3f, 0x3a, 0xf1, 0x3d, 0x49, 0xee, 0x15, 0x59, 0x7f, 0xde, 0x3d, 0x7f, 0x6a, 0x97, 0x76,
	0xca, 0xe4, 0x97, 0xb2, 0x1e, 0x75, 0xe3, 0xee, 0x8f, 0x85, 0xba, 0xcf, 0xbd, 0x88, 0x3b, 0xf7,
	0x2f, 0xc8, 0x95, 0x7a, 0xdf, 0x87, 0xd5, 0xfc, 0x2a, 0x26, 0xcd, 0x09, 0xc2, 0x72, 0x83, 0xd1,
	0xb9, 0x33, 0x35, 0x7d, 0xaa, 0x36, 0x84, 0xe5, 0xe1, 0xc5, 0x40, 0xb6, 0x0b, 0x85, 0x8c, 0x59,
	0x3a, 0xce, 0xed, 0x29, 0xa9, 0xb3, 0x59, 0xce, 0x2d, 0x01, 0x52, 0x2c, 0x63, 0xdc, 0x0e, 0x72,
	0x9a, 0xd3, 0x92, 0x67, 0x9d, 0x1c, 0x9e, 0xf9, 0x85, 0x4e, 0x8e, 0x5d, 0x38, 0x85, 0x4e, 0x8e,
	0x5f, 0x24, 0xb4, 0x44, 0x5a, 0xb0, 0x90, 0xb9, 0x03, 0x90, 0x5b, 0x05, 0xfc, 0xa3, 0x77, 0x29,
	0x67, 0x6b, 0x1a, 0xd2, 0x54, 0x4f, 0x17, 0x96, 0x86, 0x76, 0x02, 0xf9, 0x5f, 0x01, 0xfb, 0xb8,
	0x1d, 0xe6, 0x6c, 0x4f, 0x47, 0x9c, 0x6a, 0x73, 0x01, 0xce, 0x66, 0x37, 0xd9, 0x3c, 0x97, 0x3b,
	0xb3, 0x5f, 0x9c, 0x5b, 0x53, 0x50, 0xa6, 0x4a, 0x98, 0x99, 0x8f, 0x99, 0x9f, 0x1a, 0xd7, 0x0a,
	0xb8, 0xcd, 0x1f, 0x10, 0xa7, 0x68, 0x7a, 0x9e, 0x09, 0xa0, 0x25, 0xf2, 0x02, 0xaa, 0xfa, 0xe5,
	0x5d, 0x38, 0x0c, 0x93, 0x27, 0x7c, 0xe1, 0xa4, 0xca, 0xbe, 0xdb, 0x69, 0xe9, 0xf1, 0xf2, 0xeb,
	0x7a, 0x4c, 0x20, 0x22, 0xf7, 0x8f, 0x99, 0xd2, 0xdb, 0x39, 0xf3, 0x33, 0xed, 0xee, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5e, 0x9d, 0x9a, 0xa7, 0x8b, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CompactTxStreamerClient is the client API for CompactTxStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompactTxStreamerClient interface {
	// Compact Blocks
	GetLatestBlock(ctx context.Context, in *ChainSpec, opts ...grpc.CallOption) (*BlockID, error)
	GetBlock(ctx context.Context, in *BlockID, opts ...grpc.CallOption) (*CompactBlock, error)
	GetBlockRange(ctx context.Context, in *BlockRange, opts ...grpc.CallOption) (CompactTxStreamer_GetBlockRangeClient, error)
	// Transactions
	GetTransaction(ctx context.Context, in *TxFilter, opts ...grpc.CallOption) (*RawTransaction, error)
	SendTransaction(ctx context.Context, in *RawTransaction, opts ...grpc.CallOption) (*SendResponse, error)
	// t-Address support
	GetAddressTxids(ctx context.Context, in *TransparentAddressBlockFilter, opts ...grpc.CallOption) (CompactTxStreamer_GetAddressTxidsClient, error)
	// Identity
	RegisterNameCommitment(ctx context.Context, in *RegisterNameCommitmentRequest, opts ...grpc.CallOption) (*RegisterNameCommitmentResponse, error)
	RegisterIdentity(ctx context.Context, in *RegisterIdentityRequest, opts ...grpc.CallOption) (*RegisterIdentityResponse, error)
	RevokeIdentity(ctx context.Context, in *RevokeIdentityRequest, opts ...grpc.CallOption) (*RevokeIdentityResponse, error)
	RecoverIdentity(ctx context.Context, in *RecoverIdentityRequest, opts ...grpc.CallOption) (*RecoverIdentityResponse, error)
	UpdateIdentity(ctx context.Context, in *UpdateIdentityRequest, opts ...grpc.CallOption) (*UpdateIdentityResponse, error)
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error)
	VerifyMessage(ctx context.Context, in *VerifyMessageRequest, opts ...grpc.CallOption) (*VerifyMessageResponse, error)
	VerifyHash(ctx context.Context, in *VerifyHashRequest, opts ...grpc.CallOption) (*VerifyHashResponse, error)
	// Misc
	GetLightdInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LightdInfo, error)
	Ping(ctx context.Context, in *Duration, opts ...grpc.CallOption) (*PingResponse, error)
}

type compactTxStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewCompactTxStreamerClient(cc grpc.ClientConnInterface) CompactTxStreamerClient {
	return &compactTxStreamerClient{cc}
}

func (c *compactTxStreamerClient) GetLatestBlock(ctx context.Context, in *ChainSpec, opts ...grpc.CallOption) (*BlockID, error) {
	out := new(BlockID)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) GetBlock(ctx context.Context, in *BlockID, opts ...grpc.CallOption) (*CompactBlock, error) {
	out := new(CompactBlock)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) GetBlockRange(ctx context.Context, in *BlockRange, opts ...grpc.CallOption) (CompactTxStreamer_GetBlockRangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CompactTxStreamer_serviceDesc.Streams[0], "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRange", opts...)
	if err != nil {
		return nil, err
	}
	x := &compactTxStreamerGetBlockRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CompactTxStreamer_GetBlockRangeClient interface {
	Recv() (*CompactBlock, error)
	grpc.ClientStream
}

type compactTxStreamerGetBlockRangeClient struct {
	grpc.ClientStream
}

func (x *compactTxStreamerGetBlockRangeClient) Recv() (*CompactBlock, error) {
	m := new(CompactBlock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *compactTxStreamerClient) GetTransaction(ctx context.Context, in *TxFilter, opts ...grpc.CallOption) (*RawTransaction, error) {
	out := new(RawTransaction)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) SendTransaction(ctx context.Context, in *RawTransaction, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) GetAddressTxids(ctx context.Context, in *TransparentAddressBlockFilter, opts ...grpc.CallOption) (CompactTxStreamer_GetAddressTxidsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CompactTxStreamer_serviceDesc.Streams[1], "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressTxids", opts...)
	if err != nil {
		return nil, err
	}
	x := &compactTxStreamerGetAddressTxidsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CompactTxStreamer_GetAddressTxidsClient interface {
	Recv() (*RawTransaction, error)
	grpc.ClientStream
}

type compactTxStreamerGetAddressTxidsClient struct {
	grpc.ClientStream
}

func (x *compactTxStreamerGetAddressTxidsClient) Recv() (*RawTransaction, error) {
	m := new(RawTransaction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *compactTxStreamerClient) RegisterNameCommitment(ctx context.Context, in *RegisterNameCommitmentRequest, opts ...grpc.CallOption) (*RegisterNameCommitmentResponse, error) {
	out := new(RegisterNameCommitmentResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RegisterNameCommitment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) RegisterIdentity(ctx context.Context, in *RegisterIdentityRequest, opts ...grpc.CallOption) (*RegisterIdentityResponse, error) {
	out := new(RegisterIdentityResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RegisterIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) RevokeIdentity(ctx context.Context, in *RevokeIdentityRequest, opts ...grpc.CallOption) (*RevokeIdentityResponse, error) {
	out := new(RevokeIdentityResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RevokeIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) RecoverIdentity(ctx context.Context, in *RecoverIdentityRequest, opts ...grpc.CallOption) (*RecoverIdentityResponse, error) {
	out := new(RecoverIdentityResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RecoverIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) UpdateIdentity(ctx context.Context, in *UpdateIdentityRequest, opts ...grpc.CallOption) (*UpdateIdentityResponse, error) {
	out := new(UpdateIdentityResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/UpdateIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error) {
	out := new(GetIdentityResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) VerifyMessage(ctx context.Context, in *VerifyMessageRequest, opts ...grpc.CallOption) (*VerifyMessageResponse, error) {
	out := new(VerifyMessageResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/VerifyMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) VerifyHash(ctx context.Context, in *VerifyHashRequest, opts ...grpc.CallOption) (*VerifyHashResponse, error) {
	out := new(VerifyHashResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/VerifyHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) GetLightdInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LightdInfo, error) {
	out := new(LightdInfo)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactTxStreamerClient) Ping(ctx context.Context, in *Duration, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.CompactTxStreamer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompactTxStreamerServer is the server API for CompactTxStreamer service.
type CompactTxStreamerServer interface {
	// Compact Blocks
	GetLatestBlock(context.Context, *ChainSpec) (*BlockID, error)
	GetBlock(context.Context, *BlockID) (*CompactBlock, error)
	GetBlockRange(*BlockRange, CompactTxStreamer_GetBlockRangeServer) error
	// Transactions
	GetTransaction(context.Context, *TxFilter) (*RawTransaction, error)
	SendTransaction(context.Context, *RawTransaction) (*SendResponse, error)
	// t-Address support
	GetAddressTxids(*TransparentAddressBlockFilter, CompactTxStreamer_GetAddressTxidsServer) error
	// Identity
	RegisterNameCommitment(context.Context, *RegisterNameCommitmentRequest) (*RegisterNameCommitmentResponse, error)
	RegisterIdentity(context.Context, *RegisterIdentityRequest) (*RegisterIdentityResponse, error)
	RevokeIdentity(context.Context, *RevokeIdentityRequest) (*RevokeIdentityResponse, error)
	RecoverIdentity(context.Context, *RecoverIdentityRequest) (*RecoverIdentityResponse, error)
	UpdateIdentity(context.Context, *UpdateIdentityRequest) (*UpdateIdentityResponse, error)
	GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error)
	VerifyMessage(context.Context, *VerifyMessageRequest) (*VerifyMessageResponse, error)
	VerifyHash(context.Context, *VerifyHashRequest) (*VerifyHashResponse, error)
	// Misc
	GetLightdInfo(context.Context, *Empty) (*LightdInfo, error)
	Ping(context.Context, *Duration) (*PingResponse, error)
}

// UnimplementedCompactTxStreamerServer can be embedded to have forward compatible implementations.
type UnimplementedCompactTxStreamerServer struct {
}

func (*UnimplementedCompactTxStreamerServer) GetLatestBlock(ctx context.Context, req *ChainSpec) (*BlockID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBlock not implemented")
}
func (*UnimplementedCompactTxStreamerServer) GetBlock(ctx context.Context, req *BlockID) (*CompactBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (*UnimplementedCompactTxStreamerServer) GetBlockRange(req *BlockRange, srv CompactTxStreamer_GetBlockRangeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBlockRange not implemented")
}
func (*UnimplementedCompactTxStreamerServer) GetTransaction(ctx context.Context, req *TxFilter) (*RawTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedCompactTxStreamerServer) SendTransaction(ctx context.Context, req *RawTransaction) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedCompactTxStreamerServer) GetAddressTxids(req *TransparentAddressBlockFilter, srv CompactTxStreamer_GetAddressTxidsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAddressTxids not implemented")
}
func (*UnimplementedCompactTxStreamerServer) RegisterNameCommitment(ctx context.Context, req *RegisterNameCommitmentRequest) (*RegisterNameCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNameCommitment not implemented")
}
func (*UnimplementedCompactTxStreamerServer) RegisterIdentity(ctx context.Context, req *RegisterIdentityRequest) (*RegisterIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterIdentity not implemented")
}
func (*UnimplementedCompactTxStreamerServer) RevokeIdentity(ctx context.Context, req *RevokeIdentityRequest) (*RevokeIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeIdentity not implemented")
}
func (*UnimplementedCompactTxStreamerServer) RecoverIdentity(ctx context.Context, req *RecoverIdentityRequest) (*RecoverIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverIdentity not implemented")
}
func (*UnimplementedCompactTxStreamerServer) UpdateIdentity(ctx context.Context, req *UpdateIdentityRequest) (*UpdateIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIdentity not implemented")
}
func (*UnimplementedCompactTxStreamerServer) GetIdentity(ctx context.Context, req *GetIdentityRequest) (*GetIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (*UnimplementedCompactTxStreamerServer) VerifyMessage(ctx context.Context, req *VerifyMessageRequest) (*VerifyMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMessage not implemented")
}
func (*UnimplementedCompactTxStreamerServer) VerifyHash(ctx context.Context, req *VerifyHashRequest) (*VerifyHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyHash not implemented")
}
func (*UnimplementedCompactTxStreamerServer) GetLightdInfo(ctx context.Context, req *Empty) (*LightdInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLightdInfo not implemented")
}
func (*UnimplementedCompactTxStreamerServer) Ping(ctx context.Context, req *Duration) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterCompactTxStreamerServer(s *grpc.Server, srv CompactTxStreamerServer) {
	s.RegisterService(&_CompactTxStreamer_serviceDesc, srv)
}

func _CompactTxStreamer_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).GetLatestBlock(ctx, req.(*ChainSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).GetBlock(ctx, req.(*BlockID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_GetBlockRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockRange)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompactTxStreamerServer).GetBlockRange(m, &compactTxStreamerGetBlockRangeServer{stream})
}

type CompactTxStreamer_GetBlockRangeServer interface {
	Send(*CompactBlock) error
	grpc.ServerStream
}

type compactTxStreamerGetBlockRangeServer struct {
	grpc.ServerStream
}

func (x *compactTxStreamerGetBlockRangeServer) Send(m *CompactBlock) error {
	return x.ServerStream.SendMsg(m)
}

func _CompactTxStreamer_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).GetTransaction(ctx, req.(*TxFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).SendTransaction(ctx, req.(*RawTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_GetAddressTxids_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransparentAddressBlockFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompactTxStreamerServer).GetAddressTxids(m, &compactTxStreamerGetAddressTxidsServer{stream})
}

type CompactTxStreamer_GetAddressTxidsServer interface {
	Send(*RawTransaction) error
	grpc.ServerStream
}

type compactTxStreamerGetAddressTxidsServer struct {
	grpc.ServerStream
}

func (x *compactTxStreamerGetAddressTxidsServer) Send(m *RawTransaction) error {
	return x.ServerStream.SendMsg(m)
}

func _CompactTxStreamer_RegisterNameCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNameCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).RegisterNameCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RegisterNameCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).RegisterNameCommitment(ctx, req.(*RegisterNameCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_RegisterIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).RegisterIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RegisterIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).RegisterIdentity(ctx, req.(*RegisterIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_RevokeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).RevokeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RevokeIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).RevokeIdentity(ctx, req.(*RevokeIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_RecoverIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).RecoverIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/RecoverIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).RecoverIdentity(ctx, req.(*RecoverIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_UpdateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).UpdateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/UpdateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).UpdateIdentity(ctx, req.(*UpdateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_VerifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).VerifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/VerifyMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).VerifyMessage(ctx, req.(*VerifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_VerifyHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).VerifyHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/VerifyHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).VerifyHash(ctx, req.(*VerifyHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_GetLightdInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).GetLightdInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).GetLightdInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactTxStreamer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Duration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactTxStreamerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.CompactTxStreamer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactTxStreamerServer).Ping(ctx, req.(*Duration))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompactTxStreamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cash.z.wallet.sdk.rpc.CompactTxStreamer",
	HandlerType: (*CompactTxStreamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestBlock",
			Handler:    _CompactTxStreamer_GetLatestBlock_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _CompactTxStreamer_GetBlock_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _CompactTxStreamer_GetTransaction_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _CompactTxStreamer_SendTransaction_Handler,
		},
		{
			MethodName: "RegisterNameCommitment",
			Handler:    _CompactTxStreamer_RegisterNameCommitment_Handler,
		},
		{
			MethodName: "RegisterIdentity",
			Handler:    _CompactTxStreamer_RegisterIdentity_Handler,
		},
		{
			MethodName: "RevokeIdentity",
			Handler:    _CompactTxStreamer_RevokeIdentity_Handler,
		},
		{
			MethodName: "RecoverIdentity",
			Handler:    _CompactTxStreamer_RecoverIdentity_Handler,
		},
		{
			MethodName: "UpdateIdentity",
			Handler:    _CompactTxStreamer_UpdateIdentity_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _CompactTxStreamer_GetIdentity_Handler,
		},
		{
			MethodName: "VerifyMessage",
			Handler:    _CompactTxStreamer_VerifyMessage_Handler,
		},
		{
			MethodName: "VerifyHash",
			Handler:    _CompactTxStreamer_VerifyHash_Handler,
		},
		{
			MethodName: "GetLightdInfo",
			Handler:    _CompactTxStreamer_GetLightdInfo_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CompactTxStreamer_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlockRange",
			Handler:       _CompactTxStreamer_GetBlockRange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAddressTxids",
			Handler:       _CompactTxStreamer_GetAddressTxids_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
